name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Build cppcheck
      run: |
        git clone https://github.com/danmar/cppcheck.git
        pushd cppcheck
        make -j$(nproc)
        ls -la
        popd
    - name: run cppcheck
      run: |
       cppcheck/cppcheck --enable=all --inconclusive *.cpp *.c
